# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
